// File: src/features/reservations/api/reservations.api.ts

/**
 * Asancha Reservations API
 *
 * Purpose:
 * Provides typed authenticated API functions for investor reservation list,
 * creation, detail, cancellation, and safe activity timeline workflows.
 *
 * Responsibilities:
 * - Retrieve reservations belonging to the active investor profile.
 * - Create reservation requests for eligible listings.
 * - Retrieve one reservation by public ID.
 * - Cancel an eligible current-user reservation.
 * - Build reservation query strings.
 *
 * Security notes:
 * - All requests use authenticated API helpers.
 * - This module does not call staff confirmation, rejection, forced expiry, or
 *   administrative cancellation endpoints.
 * - Payment references are generated by the backend.
 * - Backend listing, investor, verification, proof-of-funds, policy, payment,
 *   duplicate, expiry, ownership, and lifecycle checks remain final.
 */

import {
    authApiGet,
    authApiPost,
} from "../../../lib/api/auth-fetch";

import { RESERVATIONS_API_ENDPOINTS } from "../constants/reservations.constants";
import type {
    CancelReservationPayload,
    CancelReservationResult,
    CreateReservationPayload,
    CreateReservationResult,
    ReservationCollection,
    ReservationDetail,
    ReservationFilters,
    ReservationQuery,
} from "../types/reservations.types";

function appendString(
    searchParams: URLSearchParams,
    key: string,
    value: string | null | undefined,
): void {
    const normalizedValue = value?.trim();

    if (normalizedValue) {
        searchParams.set(key, normalizedValue);
    }
}

function appendStringArray(
    searchParams: URLSearchParams,
    key: string,
    values: readonly string[] | undefined,
): void {
    if (!values?.length) {
        return;
    }

    for (const value of values) {
        const normalizedValue = value.trim();

        if (normalizedValue) {
            searchParams.append(key, normalizedValue);
        }
    }
}

function appendNumber(
    searchParams: URLSearchParams,
    key: string,
    value: number | undefined,
): void {
    if (
        value !== undefined &&
        Number.isFinite(value)
    ) {
        searchParams.set(key, String(value));
    }
}

function appendBoolean(
    searchParams: URLSearchParams,
    key: string,
    value: boolean | undefined,
): void {
    if (value !== undefined) {
        searchParams.set(key, String(value));
    }
}

function createReservationQueryString(
    query:
        | ReservationQuery
        | Partial<ReservationFilters>,
): string {
    const searchParams = new URLSearchParams();

    appendString(
        searchParams,
        "search",
        query.search,
    );

    appendStringArray(
        searchParams,
        "statuses",
        query.statuses,
    );

    appendStringArray(
        searchParams,
        "paymentStatuses",
        query.paymentStatuses,
    );

    appendString(
        searchParams,
        "listingPublicId",
        query.listingPublicId,
    );

    appendString(
        searchParams,
        "propertyPublicId",
        query.propertyPublicId,
    );

    appendBoolean(
        searchParams,
        "requiresAction",
        query.requiresAction ?? undefined,
    );

    appendBoolean(
        searchParams,
        "expiringSoon",
        query.expiringSoon ?? undefined,
    );

    appendBoolean(
        searchParams,
        "dealPackAccessGranted",
        query.dealPackAccessGranted ?? undefined,
    );

    appendString(
        searchParams,
        "sort",
        query.sort,
    );

    appendNumber(
        searchParams,
        "page",
        query.page,
    );

    appendNumber(
        searchParams,
        "pageSize",
        query.pageSize,
    );

    const queryString = searchParams.toString();

    return queryString ? `?${queryString}` : "";
}

async function getReservations(
    query:
        | ReservationQuery
        | Partial<ReservationFilters> = {},
): Promise<ReservationCollection> {
    const queryString =
        createReservationQueryString(query);

    return authApiGet<ReservationCollection>(
        `${RESERVATIONS_API_ENDPOINTS.mine}${queryString}`,
    );
}

async function getReservation(
    reservationPublicId: string,
): Promise<ReservationDetail> {
    return authApiGet<ReservationDetail>(
        RESERVATIONS_API_ENDPOINTS.reservation(
            reservationPublicId,
        ),
    );
}

async function createReservation(
    payload: CreateReservationPayload,
): Promise<CreateReservationResult> {
    return authApiPost<
        CreateReservationResult,
        CreateReservationPayload
    >(
        RESERVATIONS_API_ENDPOINTS.create,
        payload,
    );
}

async function cancelReservation(
    reservationPublicId: string,
    payload: CancelReservationPayload,
): Promise<CancelReservationResult> {
    return authApiPost<
        CancelReservationResult,
        CancelReservationPayload
    >(
        RESERVATIONS_API_ENDPOINTS.cancel(
            reservationPublicId,
        ),
        payload,
    );
}

export const reservationsApi = {
    getReservations,
    getReservation,
    createReservation,
    cancelReservation,
} as const;
