// File: src/features/reservations/constants/reservations.constants.ts

/**
 * Asancha Reservation Constants
 *
 * Purpose:
 * Defines current-user reservation endpoints, routes, lifecycle labels,
 * default filters, pagination values, and safe user-facing messages.
 *
 * Responsibilities:
 * - Keep reservation API paths in one place.
 * - Define reservation and payment status options.
 * - Provide reservation, payment, listing, and deal-pack routes.
 * - Provide default filter state.
 * - Provide safe lifecycle and locked-action messages.
 *
 * Security notes:
 * - Admin confirmation, rejection, expiry, and forced cancellation endpoints
 *   must not appear here.
 * - Frontend constants do not grant permission to reserve or cancel.
 * - Reservation payment references must be generated by the backend.
 */

import type {
    ReservationFilters,
    ReservationPaymentStatus,
    ReservationStatus,
} from "../types/reservations.types";

export const RESERVATIONS_API_ENDPOINTS = {
    create: "/reservations",
    mine: "/reservations",

    reservation: (
        reservationPublicId: string,
    ): string =>
        `/ reservations / ${encodeURIComponent(
            reservationPublicId,
        )
        } `,

    cancel: (
        reservationPublicId: string,
    ): string =>
        `/ reservations / ${encodeURIComponent(
            reservationPublicId,
        )
        }/cancel`,

    activities: (
        reservationPublicId: string,
    ): string =>
        `/reservations/${encodeURIComponent(
            reservationPublicId,
        )}/activities`,
} as const;

export const RESERVATION_PAGE_ROUTES = {
    root: "/reservations",

    detail: (
        reservationPublicId: string,
    ): string =>
        `/reservations/${encodeURIComponent(
            reservationPublicId,
        )}`,

    cancel: (
        reservationPublicId: string,
    ): string =>
        `/reservations/${encodeURIComponent(
            reservationPublicId,
        )}/cancel`,

    marketplace: "/marketplace",

    listing: (listingSlug: string): string =>
        `/marketplace/${encodeURIComponent(
            listingSlug,
        )}`,

    payment: (paymentPublicId: string): string =>
        `/payments/${encodeURIComponent(
            paymentPublicId,
        )}`,

    verification: "/verification",
    documents: "/documents",

    dealPack: (
        reservationPublicId: string,
    ): string =>
        `/reservations/${encodeURIComponent(
            reservationPublicId,
        )}/deal-pack`,
} as const;

export const RESERVATION_STATUS_OPTIONS = [
    {
        value: "draft",
        label: "Draft",
    },
    {
        value: "requested",
        label: "Requested",
    },
    {
        value: "pending_payment",
        label: "Payment required",
    },
    {
        value: "payment_submitted",
        label: "Payment submitted",
    },
    {
        value: "under_review",
        label: "Under review",
    },
    {
        value: "confirmed",
        label: "Confirmed",
    },
    {
        value: "rejected",
        label: "Rejected",
    },
    {
        value: "cancelled",
        label: "Cancelled",
    },
    {
        value: "expired",
        label: "Expired",
    },
    {
        value: "failed",
        label: "Failed",
    },
    {
        value: "completed",
        label: "Completed",
    },
] as const satisfies ReadonlyArray<{
    value: ReservationStatus;
    label: string;
}>;

export const RESERVATION_PAYMENT_STATUS_OPTIONS = [
    {
        value: "not_required",
        label: "Not required",
    },
    {
        value: "not_generated",
        label: "Not generated",
    },
    {
        value: "pending",
        label: "Pending",
    },
    {
        value: "submitted",
        label: "Submitted",
    },
    {
        value: "paid",
        label: "Paid",
    },
    {
        value: "rejected",
        label: "Rejected",
    },
    {
        value: "expired",
        label: "Expired",
    },
    {
        value: "cancelled",
        label: "Cancelled",
    },
    {
        value: "failed",
        label: "Failed",
    },
    {
        value: "refunded",
        label: "Refunded",
    },
] as const satisfies ReadonlyArray<{
    value: ReservationPaymentStatus;
    label: string;
}>;

export const RESERVATION_SORT_OPTIONS = [
    {
        value: "newest",
        label: "Newest first",
    },
    {
        value: "oldest",
        label: "Oldest first",
    },
    {
        value: "updated_recently",
        label: "Recently updated",
    },
    {
        value: "expiry_soonest",
        label: "Expiring soonest",
    },
    {
        value: "amount_low_to_high",
        label: "Amount: low to high",
    },
    {
        value: "amount_high_to_low",
        label: "Amount: high to low",
    },
    {
        value: "status",
        label: "Status",
    },
] as const;

export const RESERVATION_PAGE_SIZE_OPTIONS = [
    10,
    20,
    30,
    50,
] as const;

export const RESERVATION_MAX_PAGE_SIZE = 50;

export const DEFAULT_RESERVATION_FILTERS: ReservationFilters = {
    search: "",
    statuses: [],
    paymentStatuses: [],

    listingPublicId: null,
    propertyPublicId: null,

    requiresAction: null,
    expiringSoon: null,
    dealPackAccessGranted: null,

    sort: "updated_recently",
    page: 1,
    pageSize: 20,
};

export const INITIAL_CREATE_RESERVATION_VALUES = {
    listingPublicId: "",
    reservationTermsAccepted: false,
    informationAccurateConfirmed: false,
    paymentRequirementAcknowledged: false,
} as const;

export const INITIAL_CANCEL_RESERVATION_VALUES = {
    reason: "",
    cancellationConfirmed: false,
} as const;

export const RESERVATION_SAFE_MESSAGES = {
    loadError:
        "We could not load your reservations. Please refresh the page.",

    detailLoadError:
        "We could not load this reservation. It may not exist or may not belong to your active investor profile.",

    createError:
        "We could not request this reservation. Review the listing availability and your account requirements before trying again.",

    created:
        "Your reservation request has been created.",

    paymentGenerated:
        "A payment requirement has been generated for this reservation.",

    cancellationError:
        "We could not cancel this reservation. Its current status may not allow cancellation.",

    cancelled:
        "The reservation has been cancelled.",

    requested:
        "Your reservation request has been received.",

    pendingPayment:
        "Complete the reservation payment before the payment reference expires.",

    paymentSubmitted:
        "Your payment has been submitted for verification. The reservation is not yet confirmed.",

    underReview:
        "Your reservation is being reviewed.",

    confirmed:
        "Your reservation has been confirmed.",

    rejected:
        "This reservation could not be approved. Review the safe reason and next action.",

    expired:
        "This reservation has expired and no longer holds the listing.",

    failed:
        "This reservation could not be completed.",

    completed:
        "This reservation process has been completed.",

    listingUnavailable:
        "This listing is not currently available for reservation.",

    duplicateReservation:
        "You already have an active reservation for this listing.",

    investorRequired:
        "An active investor profile is required to reserve a deal.",

    verificationPending:
        "Investor verification is pending.",

    proofOfFundsRequired:
        "Approved proof of funds is required for this reservation.",

    paymentRequired:
        "Reservation payment is required.",

    paymentNotVerified:
        "Payment has not been verified.",

    suspendedAccount:
        "Your account is currently unable to create reservations.",

    confirmationControlled:
        "Reservation confirmation remains subject to listing availability, payment verification, and backend review.",

    dealPackRestricted:
        "Deal-pack access becomes available only after the reservation is confirmed and all required payment conditions are satisfied.",
} as const;

export function getReservationStatusLabel(
    status: ReservationStatus,
): string {
    return (
        RESERVATION_STATUS_OPTIONS.find(
            (option) => option.value === status,
        )?.label ?? status
    );
}

export function getReservationPaymentStatusLabel(
    status: ReservationPaymentStatus,
): string {
    return (
        RESERVATION_PAYMENT_STATUS_OPTIONS.find(
            (option) => option.value === status,
        )?.label ?? status
    );
}
